"use client";
import { useEffect, useState } from "react";
import {
  TrendingUp, TrendingDown, Award, Users, BarChart3,
  Clock, Star, Zap, Globe, BookOpen, ArrowUp, ArrowDown,
  Download, FileText
} from "lucide-react";

interface SkillAnalytic {
  skill: string;
  supply: number;
  demand: number;
  gap: number;
}

interface OverviewData {
  totalUsers: number;
  totalProfiles: number;
  activeMatches: number;
  pendingMatches: number;
  totalSessions: number;
  totalHours: number;
  avgRating: number;
}

export default function CommunityPage() {
  const [overview, setOverview] = useState<OverviewData | null>(null);
  const [skillAnalytics, setSkillAnalytics] = useState<SkillAnalytic[]>([]);
  const [inDemand, setInDemand] = useState<SkillAnalytic[]>([]);
  const [oversupplied, setOversupplied] = useState<SkillAnalytic[]>([]);
  const [languages, setLanguages] = useState<Record<string, number>>({});
  const [styles, setStyles] = useState<Record<string, number>>({});
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      const res = await fetch("/api/analytics");
      const data = await res.json();
      setOverview(data.overview);
      setSkillAnalytics(data.skillAnalytics || []);
      setInDemand(data.inDemand || []);
      setOversupplied(data.oversupplied || []);
      setLanguages(data.languageCounts || {});
      setStyles(data.styleCounts || {});
      setLoading(false);
    }
    load();
  }, []);

  function downloadReport() {
    const report = generateReportText();
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `apnova-report-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function generateReportText() {
    const lines = [
      "═══════════════════════════════════════",
      "  APNOVA — COMMUNITY SKILLS REPORT",
      `  Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
      "═══════════════════════════════════════",
      "",
      "PLATFORM OVERVIEW",
      `  Total Users:       ${overview?.totalUsers || 0}`,
      `  Active Matches:    ${overview?.activeMatches || 0}`,
      `  Pending Matches:   ${overview?.pendingMatches || 0}`,
      `  Total Sessions:    ${overview?.totalSessions || 0}`,
      `  Total Hours:       ${overview?.totalHours || 0}`,
      `  Avg Session Rating: ${overview?.avgRating || 0}/5`,
      "",
      "TOP IN-DEMAND SKILLS (Gap = Demand − Supply)",
      ...inDemand.map(s => `  ${s.skill.padEnd(25)} Supply: ${s.supply}  Demand: ${s.demand}  Gap: +${s.gap}`),
      "",
      "OVERSUPPLIED SKILLS",
      ...oversupplied.map(s => `  ${s.skill.padEnd(25)} Supply: ${s.supply}  Demand: ${s.demand}  Gap: ${s.gap}`),
      "",
      "ALL SKILLS ANALYSIS",
      ...skillAnalytics.map(s => `  ${s.skill.padEnd(25)} Supply: ${s.supply}  Demand: ${s.demand}  Gap: ${s.gap > 0 ? "+" : ""}${s.gap}`),
      "",
      "LANGUAGES SPOKEN",
      ...Object.entries(languages).sort((a, b) => b[1] - a[1]).map(([lang, count]) => `  ${lang.padEnd(20)} ${count} user(s)`),
      "",
      "LEARNING STYLES",
      ...Object.entries(styles).sort((a, b) => b[1] - a[1]).map(([style, count]) => `  ${style.padEnd(20)} ${count} user(s)`),
      "",
      "RECOMMENDATIONS",
      "  • Organizations should focus on building mentor pipelines for high-demand skills.",
      "  • Cross-language exchanges offer significant growth opportunities.",
      "  • Project-based and interactive learners dominate — design curricula accordingly.",
      "",
      "═══════════════════════════════════════",
      "  Report generated by APnova Analytics Engine",
      "═══════════════════════════════════════",
    ];
    return lines.join("\n");
  }

  if (loading) {
    return (
      <div className="min-h-[80vh] flex items-center justify-center">
        <div className="relative">
          <div className="w-12 h-12 border-2 border-brand-500/30 rounded-full" />
          <div className="absolute inset-0 w-12 h-12 border-2 border-brand-500 border-t-transparent rounded-full animate-spin" />
        </div>
      </div>
    );
  }

  const maxBar = Math.max(...skillAnalytics.map(s => Math.max(s.supply, s.demand)), 1);
  const maxGap = Math.max(...skillAnalytics.map(s => Math.abs(s.gap)), 1);

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8 space-y-8">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-extrabold">Community Skill Analytics</h1>
          <p className="text-sm text-slate-400 mt-1">Platform-wide insights on skill supply, demand, and workforce gaps.</p>
        </div>
        <button onClick={downloadReport} className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white/[0.06] hover:bg-white/[0.1] border border-white/[0.08] text-sm font-semibold text-slate-200 transition-all hover:scale-[1.02]">
          <Download className="w-4 h-4" /> Download Report
        </button>
      </div>

      {/* Overview Stats */}
      {overview && (
        <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-3">
          {[
            { label: "Users", value: overview.totalUsers, icon: Users, color: "text-brand-400", bg: "bg-brand-500/10" },
            { label: "Profiles", value: overview.totalProfiles, icon: BookOpen, color: "text-emerald-400", bg: "bg-emerald-500/10" },
            { label: "Active", value: overview.activeMatches, icon: Zap, color: "text-amber-400", bg: "bg-amber-500/10" },
            { label: "Pending", value: overview.pendingMatches, icon: Clock, color: "text-orange-400", bg: "bg-orange-500/10" },
            { label: "Sessions", value: overview.totalSessions, icon: BarChart3, color: "text-cyan-400", bg: "bg-cyan-500/10" },
            { label: "Hours", value: overview.totalHours, icon: Clock, color: "text-rose-400", bg: "bg-rose-500/10" },
            { label: "Avg Rating", value: `${overview.avgRating}/5`, icon: Star, color: "text-amber-300", bg: "bg-amber-500/10" },
          ].map(s => (
            <div key={s.label} className="p-3 rounded-xl bg-white/[0.03] border border-white/[0.06] text-center">
              <div className={`w-7 h-7 rounded-lg ${s.bg} flex items-center justify-center mx-auto mb-1.5`}>
                <s.icon className={`w-3.5 h-3.5 ${s.color}`} />
              </div>
              <div className="text-lg font-extrabold">{s.value}</div>
              <div className="text-[10px] text-slate-500 font-medium">{s.label}</div>
            </div>
          ))}
        </div>
      )}

      {/* Supply vs Demand */}
      <div className="grid lg:grid-cols-2 gap-6">
        <div className="p-6 rounded-2xl bg-white/[0.03] border border-white/[0.06]">
          <h2 className="font-bold mb-1 flex items-center gap-2">
            <BarChart3 className="w-5 h-5 text-brand-400" /> Skill Supply vs Demand
          </h2>
          <p className="text-xs text-slate-500 mb-5">Teachers (supply) vs learners (demand) per skill</p>
          <div className="space-y-3">
            {skillAnalytics.map(s => (
              <div key={s.skill}>
                <div className="flex items-center justify-between text-xs mb-1">
                  <span className="font-medium text-slate-200">{s.skill}</span>
                  <span className={`font-bold ${s.gap > 0 ? "text-rose-400" : s.gap < 0 ? "text-emerald-400" : "text-slate-500"}`}>
                    {s.gap > 0 ? `+${s.gap} gap` : s.gap < 0 ? `${Math.abs(s.gap)} surplus` : "balanced"}
                  </span>
                </div>
                <div className="flex items-center gap-1 h-6">
                  <div className="flex-1 flex justify-end">
                    <div className="h-5 rounded-l-md bg-emerald-500/25 border border-emerald-500/15 flex items-center justify-end pr-1.5 transition-all" style={{ width: `${Math.max((s.supply / maxBar) * 100, 10)}%` }}>
                      <span className="text-[10px] font-bold text-emerald-300">{s.supply}</span>
                    </div>
                  </div>
                  <div className="w-px h-6 bg-white/15" />
                  <div className="flex-1">
                    <div className="h-5 rounded-r-md bg-rose-500/25 border border-rose-500/15 flex items-center pl-1.5 transition-all" style={{ width: `${Math.max((s.demand / maxBar) * 100, 10)}%` }}>
                      <span className="text-[10px] font-bold text-rose-300">{s.demand}</span>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
          <div className="flex items-center justify-center gap-6 mt-5 text-[11px] text-slate-500">
            <span className="flex items-center gap-1.5"><span className="w-3 h-3 rounded bg-emerald-500/25 border border-emerald-500/15" /> Supply (Teachers)</span>
            <span className="flex items-center gap-1.5"><span className="w-3 h-3 rounded bg-rose-500/25 border border-rose-500/15" /> Demand (Learners)</span>
          </div>
        </div>

        <div className="space-y-6">
          <div className="p-6 rounded-2xl bg-white/[0.03] border border-white/[0.06]">
            <h2 className="font-bold mb-4 flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-rose-400" /> Most In-Demand Skills
            </h2>
            {inDemand.length === 0 ? (
              <p className="text-xs text-slate-600">No significant demand gaps detected.</p>
            ) : (
              <div className="space-y-3">
                {inDemand.map((s, i) => (
                  <div key={s.skill} className="flex items-center gap-3">
                    <span className="text-xs font-bold text-slate-600 w-5 text-center">{i + 1}</span>
                    <div className="flex-1">
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-sm font-medium">{s.skill}</span>
                        <span className="text-xs font-bold text-rose-400 flex items-center gap-0.5">
                          <ArrowUp className="w-3 h-3" /> +{s.gap}
                        </span>
                      </div>
                      <div className="h-2 rounded-full bg-white/[0.04]">
                        <div className="h-full rounded-full bg-gradient-to-r from-rose-500 to-rose-400 transition-all" style={{ width: `${(s.gap / maxGap) * 100}%` }} />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="p-6 rounded-2xl bg-white/[0.03] border border-white/[0.06]">
            <h2 className="font-bold mb-4 flex items-center gap-2">
              <TrendingDown className="w-5 h-5 text-emerald-400" /> Oversupplied Skills
            </h2>
            {oversupplied.length === 0 ? (
              <p className="text-xs text-slate-600">No significant oversupply detected.</p>
            ) : (
              <div className="space-y-3">
                {oversupplied.map((s, i) => (
                  <div key={s.skill} className="flex items-center gap-3">
                    <span className="text-xs font-bold text-slate-600 w-5 text-center">{i + 1}</span>
                    <div className="flex-1">
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-sm font-medium">{s.skill}</span>
                        <span className="text-xs font-bold text-emerald-400 flex items-center gap-0.5">
                          <ArrowDown className="w-3 h-3" /> {Math.abs(s.gap)}
                        </span>
                      </div>
                      <div className="h-2 rounded-full bg-white/[0.04]">
                        <div className="h-full rounded-full bg-gradient-to-r from-emerald-500 to-emerald-400 transition-all" style={{ width: `${(Math.abs(s.gap) / maxGap) * 100}%` }} />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Languages & Styles */}
      <div className="grid md:grid-cols-2 gap-6">
        <div className="p-6 rounded-2xl bg-white/[0.03] border border-white/[0.06]">
          <h2 className="font-bold mb-4 flex items-center gap-2">
            <Globe className="w-5 h-5 text-brand-400" /> Languages Spoken
          </h2>
          <div className="flex flex-wrap gap-2">
            {Object.entries(languages).sort((a, b) => b[1] - a[1]).map(([lang, count]) => (
              <div key={lang} className="px-3 py-2 rounded-xl bg-white/[0.04] border border-white/[0.06] hover:bg-white/[0.07] transition">
                <span className="text-sm font-medium text-white">{lang}</span>
                <span className="text-xs text-slate-500 ml-2">{count} user{count > 1 ? "s" : ""}</span>
              </div>
            ))}
          </div>
        </div>
        <div className="p-6 rounded-2xl bg-white/[0.03] border border-white/[0.06]">
          <h2 className="font-bold mb-4 flex items-center gap-2">
            <BookOpen className="w-5 h-5 text-amber-400" /> Learning Styles
          </h2>
          <div className="space-y-3">
            {Object.entries(styles).sort((a, b) => b[1] - a[1]).map(([style, count]) => (
              <div key={style} className="flex items-center gap-3">
                <span className="text-sm font-medium capitalize flex-1">{style}</span>
                <div className="w-32 h-2.5 rounded-full bg-white/[0.04]">
                  <div className="h-full rounded-full bg-gradient-to-r from-brand-500 to-brand-400 transition-all" style={{ width: `${(count / Math.max(...Object.values(styles), 1)) * 100}%` }} />
                </div>
                <span className="text-xs text-slate-500 w-8 text-right font-medium">{count}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Community Report */}
      <div className="p-8 sm:p-10 rounded-3xl bg-gradient-to-br from-brand-950/80 to-accent-950/40 border border-brand-500/10 relative overflow-hidden">
        <div className="absolute -top-20 -right-20 w-60 h-60 bg-brand-500/5 rounded-full blur-3xl" />
        <div className="absolute -bottom-16 -left-16 w-48 h-48 bg-accent-500/5 rounded-full blur-3xl" />
        <div className="relative">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 rounded-xl bg-amber-500/15 flex items-center justify-center">
              <FileText className="w-5 h-5 text-amber-400" />
            </div>
            <div>
              <h2 className="text-2xl font-extrabold">Community Skills Report</h2>
              <p className="text-xs text-slate-500">Auto-generated insights for organizations and educators</p>
            </div>
          </div>
          <div className="space-y-3 text-slate-300 text-sm leading-relaxed">
            <p>
              Analysis of <strong className="text-white">{overview?.totalUsers || 0} registered learners</strong> shows
              {inDemand.length > 0
                ? ` strong demand for ${inDemand.slice(0, 3).map(s => s.skill).join(", ")}, with supply gaps of ${inDemand[0]?.gap || 0}+ teachers needed.`
                : " balanced supply and demand across the platform."
              }
            </p>
            <p>
              Organizations and community groups should focus on building <strong className="text-white">mentor pipelines</strong> in these high-demand areas to address workforce skill deficits.
              {oversupplied.length > 0
                ? ` Meanwhile, ${oversupplied.slice(0, 2).map(s => s.skill).join(" and ")} show healthy teacher availability — ideal for new learners to get started.`
                : ""
              }
            </p>
            <p>
              The community has logged <strong className="text-white">{overview?.totalSessions || 0} swap sessions</strong> totaling <strong className="text-white">{overview?.totalHours || 0} hours</strong> of collaborative learning,
              with an average peer rating of <strong className="text-white">{overview?.avgRating || 0}/5</strong>.
              {Object.keys(languages).length > 1 ? ` Learners span ${Object.keys(languages).length} languages, enabling rich cross-cultural exchange.` : ""}
            </p>
          </div>
          <div className="flex flex-wrap gap-2 mt-5">
            {inDemand.length > 0 && <span className="text-xs font-bold px-3 py-1.5 rounded-full bg-rose-500/12 text-rose-300 border border-rose-500/15">🔴 Critical Gap: {inDemand[0].skill}</span>}
            <span className="text-xs font-bold px-3 py-1.5 rounded-full bg-brand-500/12 text-brand-300 border border-brand-500/15">📈 Growing Demand</span>
            <span className="text-xs font-bold px-3 py-1.5 rounded-full bg-amber-500/12 text-amber-300 border border-amber-500/15">💡 Mentor Opportunity</span>
            <span className="text-xs font-bold px-3 py-1.5 rounded-full bg-emerald-500/12 text-emerald-300 border border-emerald-500/15">🌍 {Object.keys(languages).length} Languages</span>
          </div>
          <button onClick={downloadReport} className="mt-6 flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white/10 hover:bg-white/15 border border-white/10 text-sm font-semibold text-white transition-all hover:scale-[1.02]">
            <Download className="w-4 h-4" /> Download Full Report
          </button>
        </div>
      </div>
    </div>
  );
}
